### ISSUE TITLE
Change <image> node to <media> and add audio support

### ISSUE THREAD

**Issue by lkucharczyk** [lkucharczyk/mediawiki-PortableInfobox#11]
### Description
PIs already allow to embed images and videos with `<image>` tag, but there was no native way to embed audio files. Embeding audio files could be easily based of existing NodeImage code, though "image" name won't be appropiate anymore and not everyone would like to embed audio files in image tag. NodeImage could be changed to NodeMedia and add options to disable certain media types in the node and add aliases to keep backwards compatibility.

### Tasks
- [x] Rename NodeImage to NodeMedia
- [x] Allow embedding audio files
- [x] Add options to disable images, videos or audio via node parameter
- [x] Add aliases `<image>` (allow both images and videos for backwards compatibility), `<video>`, `<audio>`
- [x] Ensure it's backwards compatibile
- [x] Write new and change existing unit tests to reflect these changes

**Comment by lkucharczyk** [comment]
## Non-backwards compatible changes
- `.pi-image` class is no longer present in the `<figure>` tag with a video (`.pi-media` class is applied to **all** media elements instead)
- `.pi-image-collection` classes were changed to `.pi-media-collection`
