### ISSUE TITLE
Add support for more formats in accent colors

### ISSUE THREAD

**Issue by lkucharczyk** [lkucharczyk/mediawiki-PortableInfobox#12]
### Description
`accent-color` parameters in the `<infobox>` tag support only hex RGB colors, but it's more convenient to just type `white` or `blue` instead. Some people may also prefer other color formats like rgb() and hsl().

### Tasks
- [x] Add support for named colors.
- [x] Add support for hex RGBA values
- [x] Add support for rgb()
- [x] Add support for rgba()
- [x] Add support for hsl()
- [x] Add support for hsla()
- [x] Add new unit tests
